CREATE DATABASE ListaTreino_Exercicio_03;

USE ListaTreino_Exercicio_03;

CREATE TABLE fFORNECEDOR (
    idFORNECEDOR INT AUTO_INCREMENT,
    nomeFornecedor VARCHAR(45),
    PRIMARY KEY (idFORNECEDOR)
);

CREATE TABLE fPRINCIPIOATIVO (
    idPRINCIPIOATIVO INT AUTO_INCREMENT,
    nomePrincipioAtivo VARCHAR(60),
    PRIMARY KEY (idPRINCIPIOATIVO)
);

CREATE TABLE fMEDICAMENTO (
    idMEDICAMENTO INT AUTO_INCREMENT,
    nomeComercial VARCHAR(60),
    idPRINCIPIOATIVO_FK INT,
    idFORNECEDOR_FK INT,
    QtdEstoque INT,
    PRIMARY KEY (idMEDICAMENTO),
    FOREIGN KEY (idPRINCIPIOATIVO_FK) REFERENCES fPRINCIPIOATIVO(idPRINCIPIOATIVO),
    FOREIGN KEY (idFORNECEDOR_FK) REFERENCES fFORNECEDOR(idFORNECEDOR)
);