CREATE DATABASE ListaTreino_Exercicio_02;

USE ListaTreino_Exercicio_02;

CREATE TABLE CLIENTE (
    idCLIENTE INT AUTO_INCREMENT,
    nomeCLIENTE VARCHAR(30),
    RG_CLIENTE VARCHAR(20),
    PRIMARY KEY (idCLIENTE)
);

CREATE TABLE VENDEDOR (
    idVENDEDOR INT AUTO_INCREMENT,
    nomeVENDEDOR VARCHAR(45),
    PRIMARY KEY (idVENDEDOR)
);

CREATE TABLE PEDIDO (
    numPEDIDO INT AUTO_INCREMENT,
    DataPedido DATETIME,
    ValorPedido NUMERIC(10,2),
    VENDEDOR_idVENDEDOR_FK INT,
    CLIENTE_idCLIENTE_FK INT,
    PRIMARY KEY (numPEDIDO),
    FOREIGN KEY (VENDEDOR_idVENDEDOR_FK) REFERENCES VENDEDOR(idVENDEDOR),
    FOREIGN KEY (CLIENTE_idCLIENTE_FK) REFERENCES CLIENTE(idCLIENTE)
);